### ISSUE TITLE
Cannot Write To Graphite - Use Of Uninitialized value in string

### ISSUE THREAD

**Issue by tompurl** [joemiller/collectd-graphite#5]
I recently installed collectd 5.0 on Ubuntu 10.4 from source. I am having
trouble writing any collectd metrics to my grahite databases.

I believe that collectd is configured properly. Before I enabled the perl 
plugin, it was able to write metrics to the rrd databases. However, after
installing this plugin, nothing was ever written to Graphite.

Here's my perl plugin config:

```
<Plugin "perl">                                                                                     
        IncludeDir "/opt/collectd/share/perl/5.10.1"                                                
        BaseName "Collectd::Plugins"                                                                
        LoadPlugin "Graphite"                                                                       

        <Plugin "Graphite">                                                                         
          Buffer "256000"                                                                           
          Prefix "servers"                                                                          
          Host   "localhost"                                                                        
          Port   "2003"                                                                             
        </Plugin>                                                                                   
</Plugin>                         
```

The collectd-graphite plugin should be creating metrics that start with
"servers", right? I don't see any whisper files related to collectd under
/opt/graphite/storage/whisper/servers. Also, I don't see any folder at
/opt/graphite/storage/whisper/collectd.

There might still be an issue with how collectd is configured or installed. 
Here's how I isntalled it:

```
$ sudo apt-get build-dep collectd
$ ./configure
$ make
$ sudo make install
```

I didn't compile with the CFLAGS option that is in your docs because I was
under the impression that that was only necessary if you were using a version
of collectd that was < 4.9. 

Here's my version of libtool and libltdl-dev:

```
ii  libltdl-dev         2.2.6b-2ubuntu1     A system independent dlopen wrapper for GNU libtool
ii  libtool             2.2.6b-2ubuntu1     Generic library support script
```

And here's how I start collectd:

```
$ cd /opt/collect/bin 
$ sudo LD_PRELOAD=/usr/lib/libperl.so.5.10.1 ./collectd -C ../etc/collectd.conf -f
```

When I start collectd, here's what I get:

Syslog:

```
Jul  6 21:04:10 millhouse collectd[32120]: plugin_load_file: The global flag is not supported, libtool 2 is required for this.
Jul  6 21:04:10 millhouse collectd[32120]: perl: Initializing Perl interpreter...
Jul  6 21:04:10 millhouse collectd[32120]: Initialization complete, entering read-loop.
```

STDOUT:

The following output is written every 10 seconds: 

```
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 127.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 127.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 127.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 127.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 127.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
Use of uninitialized value in string ne at /usr/local/share/perl/5.10.1/Collectd/Plugins/Graphite.pm line 130.
```

Do you have any idea what I may be doing wrong?

Thanks in advance!

Tom Purl

**Comment by joemiller** [comment]
You may be the first to have attempted to use the plugin with collectd 5.x.

I will try to build 5.x from source and see what needs to be done to make it work.

**Comment by joemiller** [comment]
I did some more digging and I don't believe this error is preventing the plugin from sending data to graphite.  The warnings are because I am trying to do a string comparison on a non-existant variable and perl complains (warns) but it keeps going.  I never saw these errors because they only show up if you run collectd in foreground mode.  I confirmed the behavior with 4.10 as well.

I also confirmed that the plugin was correctly sending data by running netcat on port 2003 and 'catching' the data from collectd and confirmed it was in graphite format.  You could also tcpdump on port 2003 and you will see the traffic.  eg:

```
$ nc  -v -l -p 2003
listening on [any] 2003 ...
connect to [127.0.0.1] from localhost [127.0.0.1] 55886
collectd.debian_localdomain.interface-lo.if_octets.rx 7312 1309822548
collectd.debian_localdomain.interface-lo.if_octets.tx 7312 1309822548
```

There are a couple of reasons why data will be delayed when sending from collectd -> graphite: 

1)  the plugin waits until the buffer is full before sending data to graphite.  You can tune this buffer very low (only recommended for testing) by doing something like the following:

```
LoadPlugin perl
<Plugin "perl">
   ...
   <Plugin "Graphite">
        Buffer "256"  # bytes
        ...
   </Plugin>
   ...
</Plugin>
```

2) graphite/whisper will buffer data as well, and it will throttle data too.   These are tuned in carbon.conf with the variables MAX_UPDATES_PER_SECOND, MAX_CREATES_PER_MINUTE, etc.

Please confirm you can see data flowing from collectd to graphite using netcat or tcpdump with a small Buffer setting.

I will fix up the warnings you found and then close this ticket out.  However, you _should_ be getting data from collectd into graphite with the code as-is.

Also, i found a potential issue with the new FLUSH handlers in the master branch which I will open a new ticket for.

**Comment by joemiller** [comment]
fixed in ver 3

**Comment by tompurl** [comment]
On Fri, Jul 8, 2011 at 7:01 PM, joemiller
reply@reply.github.com
wrote:

> I did some more digging and I don't believe this error is preventing the plugin from sending data to graphite.

You're right. I apologize for not getting back to you sooner. I _am_
able to send metrics to graphite from collectd. I was just confused
because it took a couple of hours the first time. I meant to update
the ticket a few days ago, but other matters came up first.

I am still having issues with some monitors though. The first set of
monitors that I configured are now in Graphite, but I have configured
a few new monitors since then that have not appeared in Graphite (or
Carbon) in the last few days. I'll be sure to use the great tips below
to help me troubleshoot this (potential) issue.

I apologize if I created any extra work for you or confusion.

> The warnings are because I am trying to do a string comparison on a non-existant variable and perl complains (warns) but it keeps going.  I never saw these errors because they only show up if you run collectd in foreground mode.  I confirmed the behavior with 4.10 as well.

Ok, good. I just wanted to make sure.

> I also confirmed that the plugin was correctly sending data by running netcat on port 2003 and 'catching' the data from collectd and confirmed it was in graphite format.  You could also tcpdump on port 2003 and you will see the traffic.  eg:
> 
>    $ nc  -v -l -p 2003
>    listening on [any] 2003 ...
>    connect to [127.0.0.1] from localhost [127.0.0.1] 55886
>    collectd.debian_localdomain.interface-lo.if_octets.rx 7312 1309822548
>    collectd.debian_localdomain.interface-lo.if_octets.tx 7312 1309822548

This is an _excellent_ tip! Thank you for sharing it, and I will
definitely be using it before I submit any more bugs against this
plugin.

> There are a couple of reasons why data will be delayed when sending from collectd -> graphite:
> 
> 1)  the plugin waits until the buffer is full before sending data to graphite.
> ...
> 2) graphite/whisper will buffer data as well, and it will throttle data too.

Ok, that probably explains it. I'll keep this in mind as I
troubleshoot the other monitors.

> Please confirm you can see data flowing from collectd to graphite.  I will open 2 additional issues in github, one will be to fix the warnings that you identified, and another will be to fix an error you helped me find with the FLUSH callbacks that are on the master branch.

Sounds great! I may still be experiencing a bug, but I think the
ball's in my court to test my setup using your tips. I'll do that soon
(my power went out today, so I'll have to try tomorrow), and update
this ticket immediately thereafter.

Thanks again for your help!

Tom Purl
